language: objective-c
cache: cocoapods

before_install:
  - sudo easy_install cpp-coveralls

script:
  - make test REPORTER=pretty DST_OS=8.1

after_success:
  - make send-to-coveralls

notifications:
  slack:
    secure: KbyhYNRIbp7sLPPR08hrj73zgWYhPM+WqvmP+TlqTvmvPq87Bc4gesjbMgSEXOtoG6BLrGW0ED7XJEb3X7NF/Dh7bEzD6UyMObK9DlHKMbRHM9Bcvh+83RxiNwQBnQqNyLwoJ+jv4oukTr6E+cDwzyZIHOB4LxWtgmGPdI2N70k=
